"""rename_owner_id

Revision ID: e55142405a86
Revises: 5b34a21b4405
Create Date: 2023-12-24 22:37:40.908658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55142405a86'
down_revision: Union[str, None] = '5b34a21b4405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_constraint('subscriptions_main_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['owner_id'], ['id'])
    op.drop_column('subscriptions', 'main_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('main_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_main_id_fkey', 'subscriptions', 'users', ['main_id'], ['id'])
    op.drop_column('subscriptions', 'owner_id')
    # ### end Alembic commands ###
