version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: "qwerty"


networks:
  internal:
    driver: bridge